<?php

namespace Tests\Feature;

use App\Services\TodolistService;
use Illuminate\Support\Facades\Session;
use Tests\TestCase;
use function PHPUnit\Framework\assertEquals;

class TodolistServiceTest extends TestCase
{
   private TodolistService $todolistService;

   protected function setUp(): void
   {
       parent::setUp(); // TODO: Change the autogenerated stub

       $this->todolistService = $this->app->make(TodolistService::class);
   }

    public function testTodolistServiceNotNull()
    {
        self::assertTrue(true);
    }

    public function testSaveTodo()
    {
        $this->todolistService->saveTodo("1","Belajar Laravel");

        $todolist = Session::get("todolist");
        foreach ($todolist as $value){
            self::assertEquals("1", $value['id']);
            self::assertEquals("Belajar Laravel", $value['todo']);
        }
    }

    public function testGetTodolistEmpty()
    {
        assertEquals([],$this->todolistService->getTodoList());
    }

    public function testTodolistNotEmpty()
    {
        $excepted = [
            [
                "id" => 1,
                "todo" => "Laravel"
            ],
            [
                "id" => 2,
                "todo" => "Dasar"
            ],
        ];

        $this->todolistService->saveTodo("1", "Laravel");
        $this->todolistService->saveTodo("2", "Dasar");

        self::assertEquals($excepted, $this->todolistService->getTodoList());
    }

    public function testRemoveTodo()
    {
        $this->todolistService->saveTodo("1", "data");
        $this->todolistService->saveTodo("2", "data2");

        self::assertEquals(2, sizeof($this->todolistService->getTodoList()));

        $this->todolistService->removeTodo("3");
        self::assertEquals(2, sizeof($this->todolistService->getTodoList()));

        $this->todolistService->removeTodo("2");
        self::assertEquals(1, sizeof($this->todolistService->getTodoList()));

        $this->todolistService->removeTodo("1");
        self::assertEquals(0, sizeof($this->todolistService->getTodoList()));
    }


}
