<?php

namespace Tests\Feature;

use App\Services\TodolistService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class TodolistServiceTest extends TestCase
{
   private TodolistService $todolistService;

   protected function setUp(): void
   {
       parent::setUp(); // TODO: Change the autogenerated stub

       $this->todolistService = $this->app->make(TodolistService::class);
   }

    public function testTodolistService()
    {
        self::assertTrue(true);
    }


}
